version: '3.8'

services:
  fastapi_app:
    build: .
    container_name: lootbox_service
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"