version: '3.8'
services:
  lootbox_service:
    build: .
    container_name: lootbox_service
    environment:
      - REDIS_URI=${REDIS_URI}
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "5432:5432"
    command: redis-server --port 5432 --requirepass ${REDIS_PASSWORD}

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"